# Site settings
title: Selcouth Cycles
email: kohlkinning@gmail.com
description: Custom wheelbuilding and bicycle repair services in Denver, CO
baseurl: "/" # the subpath of your site, e.g. /blog
url: "selcouthcycles.com" # the base hostname & protocol for your site
author: Kohl Kinning
# street_address:
city: Denver
state: CO
zip_code: 80205
country: United States of America
# phone: ((716) 555-5555)

icon: fa-wrench 

# Social settings
#facebook_url:
#github_url:
instagram_url: https://www.instagram.com/selcouthcycles/?hl=en
#linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
#pinterest_url:
#slack_url:
#twitter_url: https://twitter.com/andrewbanchich

# Build settings
markdown: kramdown

sass:
style: compressed
